added previous ff schema from older version
FAIRmat-NFDI/nomad-simulations pull request #114
Opened 2024-09-10 12:20 UTC by JFRudzinski

2024-09-19 12:57 UTC, JFRudzinski commented
@Bernadette-Mohr You could already take a look at this. I have finished implementing bond potentials, and also added a more general test suite that may be useful to you in other contexts.

I will continue expanding to the other potential types, but let me know if you have any major feedback about the direction this is going.

2024-09-19 13:40 UTC, JFRudzinski commented
@JosePizarro3 @ndaelman-hu @EBB2675 @Bernadette-Mohr  FYI - I implemented a function here in `test_force_field.py` for comparing 2 nested dictionaries, that deals with some typical data types that we have in the archive. This way I just take a section that I populated in the archive and do `<section>.m_to_dict()>`, and then compare with the expected results that I input in a pytest fixture.

I'm sure it could be improved, and maybe you already have such tools in your testing, but perhaps we can collect these into one file in `tests/` so that devs can use them, and it encourages consistency in testing.

Also, I am definitely open to feedback concerning the structure of the tests.

2024-09-20 06:49 UTC, ndaelman-hu commented
> @JosePizarro3 @ndaelman-hu @EBB2675 @Bernadette-Mohr FYI - I implemented a function here in `test_force_field.py` for comparing 2 nested dictionaries, that deals with some typical data types that we have in the archive. This way I just take a section that I populated in the archive and do `<section>.m_to_dict()>`, and then compare with the expected results that I input in a pytest fixture.
> 
> I'm sure it could be improved, and maybe you already have such tools in your testing, but perhaps we can collect these into one file in `tests/` so that devs can use them, and it encourages consistency in testing.
> 
> Also, I am definitely open to feedback concerning the structure of the tests.

Regarding `assert_dict_equal`, perhaps it's easier if you list out the kind of comparison you want?
Python comes with a native implementation of `==` for most data structures, including `dict`:

```python
>> {'a': {'b': 2}, 'c': 3} == {'a': {'b': 2}, 'c': 3}
True
```

So, if all elements have to match in value (but not necessarily order), you can use the out-of-the-box definition.

If instead only a certain numerical threshold is needed, or only certain properties should be compared, I'd recursively apply a transformation / filtering to the `dict`s before comparison. If you also want to perform such comparisons on the matching `Section`s too (e.g. as with `ModelSystem`), then I'd overwrite its `__eq__`.

2024-09-20 08:45 UTC, JFRudzinski commented
@ndaelman-hu thanks for your feedback!

I did originally try to use the native python comparisons, the original function I implemented a while ago, but I believe I could not simply compare 2 dictionaries with arbitrarily nested structures and containing various and a priori unknown types...(I will have to take a look again)

Maybe I over complicated things now, but a couple examples that I needed to treat in a special way:
1. floats need to be compared with the `approx` function, and arrays of floats with `np.isclose()` 
2. np.inf is stored as a string in the archive -- I realize now that this is more of a problem with how I managed the data that I was comparing

I guess these things fall under: "If instead only a certain numerical threshold is needed, or only certain properties should be compared, I'd recursively apply a transformation / filtering to the dicts before comparison." -- what exactly do you mean by this?

2024-09-20 13:57 UTC, ndaelman-hu commented
> @ndaelman-hu thanks for your feedback!
> 
> I did originally try to use the native python comparisons, the original function I implemented a while ago, but I believe I could not simply compare 2 dictionaries with arbitrarily nested structures and containing various and a priori unknown types...(I will have to take a look again)
> 
> Maybe I over complicated things now, but a couple examples that I needed to treat in a special way:
> 
>     1. floats need to be compared with the `approx` function, and arrays of floats with `np.isclose()`
> 
>     2. np.inf is stored as a string in the archive -- I realize now that this is more of a problem with how I managed the data that I was comparing
> 
> 
> I guess these things fall under: "If instead only a certain numerical threshold is needed, or only certain properties should be compared, I'd recursively apply a transformation / filtering to the dicts before comparison." -- what exactly do you mean by this?

Indeed, in that case I'd use a recursive function, much as you are doing now, but with the type signature `dict -> dict`.
In that recursive function, I'd just catch the cases you mentioned above, convert them and leave the rest intact.

There shouldn't be any issue overwriting the values in-place, given that the object where `m_to_dict` originated from is stored separately. Else, you can use `deepcopy`.

Lastly, Python has a max. stack frames (1000). If you encounter a stack overload, feel free to reach out, and we look into it.

2025-08-12 11:50 UTC, Bernadette-Mohr reviewed
I don't have a lot to say for a review. We can discuss the scope and direction of further development in our meeting.

2025-08-12 11:50 UTC, Bernadette-Mohr commented on tests/test_force_field.py
> +        assert value1 is None, f"Unknown types'{key}': {type(value1)} != {type(value2)}"
Are we sure here that `value1 = None` is the only problem we can ever encounter here, or should we assert that `value1` and `value2` have both the same type more generally?

2025-08-12 11:50 UTC, Bernadette-Mohr commented on tests/test_force_field.py
> +MOL = 6.022140857e23
I'll research if we can extend the definition in `ureg`. I think it would be nice if we could get rid of `MOL` as a hard-coded global variable, right now I see it in many NOMAD classes.

2025-08-15 07:47 UTC, EBB2675 requested changes

2025-08-15 07:47 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +            'angle-dihedralimproper dihedral',
is this `'angle-dihedralimproper dihedral'` intended?

2025-08-15 07:47 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +    Suggested types are: harmonic, cosine, restricted_cosinse, fourier_series, urey_bradley, polynomial, tabulated
restricted_cosine

2025-08-15 07:47 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +    Section containing information about a Urey-Bradly angle potential:
Bradley

2025-08-15 07:47 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +            self.n_interactions = (
we are setting `self.n_interactions` again here, should the second assignment be `self.n_particles`

2025-08-15 07:47 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +        shape=[],
should it be of shape=['*'] as well?

2025-08-15 07:47 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +        unit='J / degree**2',
im a bit confused, sorry if this is a ridiculous comment. each cosine is dimensionless. The bracketed terms are dimensionless too. I had the feeling that each `k_m` must carry the units of energy so that `V(\theta)` has units of energy, ` unit='J'`

2025-08-15 07:57 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +        unit='J / degree**2',
also, isnt k_m technically a fourier coefficient?

2025-08-15 09:55 UTC, EBB2675 commented
one last _rookie_ question, just for my own understanding

is it the domain convention to store angles as degrees? My thinking: trig and derivatives are defined for radians, so otherwise one needs hidden pi/180 factors in every case. 

If SI units: torques become cleanly J/rad, harmonic constants J/rad**2, and Fourier coefficients  in J

2025-08-15 10:12 UTC, JFRudzinski commented on src/nomad_simulations/schema_packages/force_field.py
> +        unit='J / degree**2',
you are correct, it was just a mistake by me, I re-implemented this as RyckaertBellemansDihedral (Can you check this one and confirm it makes sense to you), I will remove this FourierSeriesAngle

2025-08-15 10:30 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +            'angle-dihedral,improper dihedral',
i think its still here

2025-08-15 10:39 UTC, JFRudzinski commented on src/nomad_simulations/schema_packages/force_field.py
> +            'angle-dihedral,improper dihedral',
I put the comma in the wrong place :facepalm:

2025-08-15 10:44 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +                    )
indeed it crashes with `AttributeError: 'numpy.ndarray' object has no attribute 'magnitude'` here.

Would it be safer here to avoid `.magnitude` on bins/forces, since in the base class they may be plain ndarrays?

2025-08-15 10:56 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +        unit='J / degree**2',
looks good from my side :+1:

2025-08-15 11:54 UTC, ndaelman-hu commented on src/nomad_simulations/schema_packages/force_field.py
> +                    )
Is not a bad idea, but this means that you have to handle the stripping and reapplying of units externally. Or you ensure they're SI.

Personally, I'd use type hinting (`ureg.Quantity`) and handle the stripping-reapplying internally.
Python isn't statically type-checked, but at least we're using `mypy`.

2025-08-15 11:56 UTC, ndaelman-hu commented
> one last _rookie_ question, just for my own understanding
> 
> is it the domain convention to store angles as degrees? My thinking: trig and derivatives are defined for radians, so otherwise one needs hidden pi/180 factors in every case.
> 
> If SI units: torques become cleanly J/rad, harmonic constants J/rad**2, and Fourier coefficients in J

It's a good question that has come up several times. Overall, NOMAD allows for users to choose their units.
By convention we use SI in the `archive` (does not store units directly), so it would end up being `rad`, I guess.

2025-08-15 11:59 UTC, ndaelman-hu commented
Was still receiving notifications for this PR. Didn't mean to butt in, but thought these replies might be helpful.
Will sign out from notifications now.

2025-08-15 12:07 UTC, JFRudzinski commented
> one last _rookie_ question, just for my own understanding
> 
> is it the domain convention to store angles as degrees? My thinking: trig and derivatives are defined for radians, so otherwise one needs hidden pi/180 factors in every case.
> 
> If SI units: torques become cleanly J/rad, harmonic constants J/rad**2, and Fourier coefficients in J

Not necessarily, it is common to use either depending on the case. I guess rad are more common in the technical usage but deg are typically used when plotting the potentials, etc.

In terms of the schema definitions, NOMAD will automatically convert for you in terms of parsing, but I guess the question is when users grab the data will they want it in radian, so I think you are right and I switched to rad now

2025-08-15 13:39 UTC, JFRudzinski commented on src/nomad_simulations/schema_packages/force_field.py
> +                    )
I avoid the normalization/derivation now if no units + added a TODO to somehow prevent or discourage use of the base classes that don't have units

2025-08-18 07:14 UTC, JFRudzinski commented
@EBB2675 could you check my changes and approve this if OK now

2025-08-18 07:33 UTC, EBB2675 approved these changes

2025-08-18 07:33 UTC, EBB2675 commented on src/nomad_simulations/schema_packages/force_field.py
> +                    if np.all([x < tol for x in energies_diff]):
only one minor question: should the consistency check use an absolute comparison with `np.abs` ? With `x<tol`, large negative deviations would pass here

2025-08-18 08:53 UTC, merged